//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Zhtx.Common.SmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Zhtx.Common.SmsService.ISmsWorker")]
    public interface ISmsWorker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWorker/Send", ReplyAction="http://tempuri.org/ISmsWorker/SendResponse")]
        string Send(string mobile, string msg_content, string corp_msg_id, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsWorker/Send", ReplyAction="http://tempuri.org/ISmsWorker/SendResponse")]
        System.Threading.Tasks.Task<string> SendAsync(string mobile, string msg_content, string corp_msg_id, string ext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsWorkerChannel : Common.Zhtx.Common.SmsService.ISmsWorker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsWorkerClient : System.ServiceModel.ClientBase<Common.Zhtx.Common.SmsService.ISmsWorker>, Common.Zhtx.Common.SmsService.ISmsWorker {
        
        public SmsWorkerClient() {
        }
        
        public SmsWorkerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsWorkerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWorkerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWorkerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Send(string mobile, string msg_content, string corp_msg_id, string ext) {
            return base.Channel.Send(mobile, msg_content, corp_msg_id, ext);
        }
        
        public System.Threading.Tasks.Task<string> SendAsync(string mobile, string msg_content, string corp_msg_id, string ext) {
            return base.Channel.SendAsync(mobile, msg_content, corp_msg_id, ext);
        }
    }
}
